theme: jekyll-theme-cayman
total: "1.500.254"
diario: "43.096"
obitos: "61.992"
obitosdiario: "1.185"
totalms: "1.496.858"
diarioms: "48.105"
obitosms: "61.884"
obitosdiarioms: "1.252"
dataref: "02/07/2020"
