theme: jekyll-theme-cayman
total: "2.168.338"
diario: "44.491"
obitos: "81.633"
obitosdiario: "1.351"
totalms: "2.159.654"
diarioms: "41.008"
obitosms: "81.487"
obitosdiarioms: "1.367"
dataref: "21/07/2020"
