theme: jekyll-theme-cayman
total: "2.865.351"
diario: "55.046"
obitos: "97.463"
obitosdiario: "1.334"
totalms: "2.859.073"
diarioms: "57.152"
obitosms: "97.256"
obitosdiarioms: "1.437"
dataref: "05/08/2020"
