theme: jekyll-theme-cayman
total: "1.867.057"
diario: "23.629"
obitos: "72.169"
obitosdiario: "609"
totalms: "1.864.681"
diarioms: "24.831"
obitosms: "72.100"
obitosdiarioms: "631"
dataref: "12/07/2020"
