theme: jekyll-theme-cayman
total: "2.810.305"
diario: "57.605"
obitos: "96.129"
obitosdiario: "1.398"
totalms: "2.801.921"
diarioms: "51.603"
obitosms: "95.819"
obitosdiarioms: "1.154"
dataref: "04/08/2020"
