theme: jekyll-theme-cayman
total: "2.734.619"
diario: "22.627"
obitos: "94.158"
obitosdiario: "489"
totalms: "2.733.677"
diarioms: "25.800"
obitosms: "94.104"
obitosdiarioms: "541"
dataref: "02/08/2020"
