theme: jekyll-theme-cayman
total: "1.345.844"
diario: "27.757"
obitos: "57.688"
obitosdiario: "534"
totalms: "1.344.143"
diarioms: "30.476"
obitosms: "57.622"
obitosdiarioms: "552"
dataref: "28/06/2020"
