theme: jekyll-theme-cayman
total: "2.615.245"
diario: "58.339"
obitos: "91.403"
obitosdiario: "1.179"
totalms: "2.610.102"
diarioms: "57.837"
obitosms: "91.263"
obitosdiarioms: "1.129"
dataref: "30/07/2020"
