theme: jekyll-theme-cayman
total: "1.113.957"
diario: "26.741"
obitos: "51.418"
obitosdiario: "747"
totalms: "1.106.470"
diarioms: "21.432"
obitosms: "51.271"
obitosdiarioms: "654"
dataref: "22/06/2020"
