theme: jekyll-theme-cayman
total: "1.409.879"
diario: "38.220"
obitos: "59.754"
obitosdiario: "1319"
totalms: "1.402.041"
diarioms: "33.846"
obitosms: "59.594"
obitosdiarioms: "1.280"
dataref: "30/06/2020"
