theme: jekyll-theme-cayman
total: "3.036.657"
diario: "21.656"
obitos: "101.170"
obitosdiario: "586"
totalms: "3.035.422"
diarioms: "23.010"
obitosms: "101.049"
obitosdiarioms: "572"
dataref: "09/08/2020"
