theme: jekyll-theme-cayman
total: "1.371.659"
diario: "25.815"
obitos: "58.435"
obitosdiario: "747"
totalms: "1.368.195"
diarioms: "24.052"
obitosms: "58.314"
obitosdiarioms: "692"
dataref: "28/06/2020"
