theme: jekyll-theme-cayman
total: "2.123.847"
diario: "23.129"
obitos: "80.282"
obitosdiario: "728"
totalms: "2.118.646"
diarioms: "20.257"
obitosms: "80.120"
obitosdiarioms: "632"
dataref: "20/07/2020"
