theme: jekyll-theme-cayman
total: "2.076.818"
diario: "23.991"
obitos: "78.853"
obitosdiario: "827"
totalms: "2.074.860"
diarioms: "28.532"
obitosms: "78.772"
obitosdiarioms: "921"
dataref: "18/07/2020"
