theme: jekyll-theme-cayman
total: "3.506.744"
diario: "43.611"
obitos: "112.460"
obitosdiario: "1.220"
totalms: "3.501.975"
diarioms: "45.323"
obitosms: "112.304"
obitosdiarioms: "1.204"
dataref: "20/08/2020"
