theme: jekyll-theme-cayman
total: "3.364.627"
diario: "21.515"
obitos: "108.690"
obitosdiario: "738"
totalms: "3.359.570"
diarioms: "19.373"
obitosms: "108.536"
obitosdiarioms: "684"
dataref: "17/08/2020"
