theme: jekyll-theme-cayman
total: "2.556.906"
diario: "68.099"
obitos: "90.224"
obitosdiario: "1.552"
totalms: "2.552.265"
diarioms: "69.074"
obitosms: "90.134"
obitosdiarioms: "1.595"
dataref: "29/07/2020"
