theme: jekyll-theme-cayman
total: "1.628.509"
diario: "23.482"
obitos: "65.600"
obitosdiario: "676"
totalms: "1.623.284"
diarioms: "20.229"
obitosms: "65.487"
obitosdiarioms: "620"
dataref: "06/07/2020"
