theme: jekyll-theme-cayman
total: "2.919.447"
diario: "54.096"
obitos: "98.681"
obitosdiario: "1.218"
totalms: "2.912.212"
diarioms: "53.139"
obitosms: "98.493"
obitosdiarioms: "1.237"
dataref: "06/08/2020"
