theme: jekyll-theme-cayman
total: "3.172.332"
diario: "55.845"
obitos: "104.349"
obitosdiario: "1.183"
totalms: "3.164.785"
diarioms: "55.155"
obitosms: "104.201"
obitosdiarioms: "1.175"
dataref: "12/08/2020"
