theme: jekyll-theme-cayman
total: "2.667.990"
diario: "52.745"
obitos: "92.604"
obitosdiario: "1.201"
totalms: "2.662.485"
diarioms: "52.383"
obitosms: "92.475"
obitosdiarioms: "1.212"
dataref: "31/07/2020"
