theme: jekyll-theme-cayman
total: "2.488.807"
diario: "39.130"
obitos: "88.672"
obitosdiario: "870"
totalms: "2.483.191"
diarioms: "40.816"
obitosms: "88.539"
obitosdiarioms: "921"
dataref: "28/07/2020"
