theme: jekyll-theme-cayman
total: "2.752.700"
diario: "18.081"
obitos: "94.731"
obitosdiario: "573"
totalms: "2.750.318"
diarioms: "16.641"
obitosms: "94.665"
obitosdiarioms: "561"
dataref: "03/08/2020"
