theme: jekyll-theme-cayman
total: "1.235.031"
diario: "41.269"
obitos: "55.095"
obitosdiario: "1.198"
totalms: "1.228.114"
diarioms: "39.483"
obitosms: "54.971"
obitosdiarioms: "1.141"
dataref: "25/06/2020"
