theme: jekyll-theme-cayman
total: "1.087.216"
diario: "16.152"
obitos: "50.671"
obitosdiario: "587"
totalms: "1.085.038"
diarioms: "17.459"
obitosms: "50.617"
obitosdiarioms: "641"
dataref: "21/06/2020"
