theme: jekyll-theme-cayman
total: "1.457.158"
diario: "47.279"
obitos: "60.807"
obitosdiario: "1.053"
totalms: "1.448.753"
diarioms: "46.712"
obitosms: "60.632"
obitosdiarioms: "1.038"
dataref: "01/07/2020"
