theme: jekyll-theme-cayman
total: "3.116.487"
diario: "53.756"
obitos: "103.166"
obitosdiario: "1.222"
totalms: "3.109.630"
diarioms: "52.160"
obitosms: "103.026"
obitosdiarioms: "1.274"
dataref: "11/08/2020"
