theme: jekyll-theme-cayman
total: "3.320.530"
diario: "37.091"
obitos: "107.341"
obitosdiario: "699"
totalms: "3.317.096"
diarioms: "41.576"
obitosms: "107.232"
obitosdiarioms: "709"
dataref: "15/08/2020"
