theme: jekyll-theme-cayman
total: "3.015.001"
diario: "44.060"
obitos: "100.584"
obitosdiario: "829"
totalms: "3.012.412"
diarioms: "49.970"
obitosms: "100.477"
obitosdiarioms: "905"
dataref: "08/08/2020"
