theme: jekyll-theme-cayman
total: "1.972.454"
diario: "39.933"
obitos: "75.562"
obitosdiario: "1.278"
totalms: "1.966.748"
diarioms: "39.924"
obitosms: "75.366"
obitosdiarioms: "1.233"
dataref: "15/07/2020"
