theme: jekyll-theme-cayman
total: "1.761.496"
diario: "41.341"
obitos: "69.289"
obitosdiario: "1.207"
totalms: "1.755.779"
diarioms: "42.619"
obitosms: "69.184"
obitosdiarioms: "1.220"
dataref: "09/07/2020"
