theme: jekyll-theme-cayman
total: "1.889.346"
diario: "22.289"
obitos: "72.967"
obitosdiario: "798"
totalms: "1.884.967"
diarioms: "20.286"
obitosms: "72.933"
obitosdiarioms: "733"
dataref: "13/07/2020"
