theme: jekyll-theme-cayman
total: "2.292.754"
diario: "57.678"
obitos: "84.233"
obitosdiario: "1.308"
totalms: "2.287.475"
diarioms: "59.961"
obitosms: "84.082"
obitosdiarioms: "1.311"
dataref: "23/07/2020"
