theme: jekyll-theme-cayman
total: "1.720.155"
diario: "44.891"
obitos: "68.082"
obitosdiario: "1.175"
totalms: "1.713.160"
diarioms: "44.571"
obitosms: "67.964"
obitosdiarioms: "1.223"
dataref: "08/07/2020"
