theme: jekyll-theme-cayman
total: "3.062.731"
diario: "26.074"
obitos: "101.944"
obitosdiario: "774"
totalms: "3.057.470"
diarioms: "22.048"
obitosms: "101.752"
obitosdiarioms: "703"
dataref: "10/08/2020"
