theme: jekyll-theme-cayman
total: "2.016.413"
diario: "43.959"
obitos: "76.855"
obitosdiario: "1.293"
totalms: "2.012.151"
diarioms: "45.403"
obitosms: "76.688"
obitosdiarioms: "1.322"
dataref: "16/07/2020"
