theme: jekyll-theme-cayman
total: "1.545.026"
diario: "44.772"
obitos: "63.305"
obitosdiario: "1.313"
totalms: "1.539.081"
diarioms: "42.223"
obitosms: "63.174"
obitosdiarioms: "1.290"
dataref: "03/07/2020"
