theme: jekyll-theme-cayman
total: "1.932.521"
diario: "43.175"
obitos: "74.284"
obitosdiario: "1.317"
totalms: "1.926.824"
diarioms: "41.857"
obitosms: "74.133"
obitosdiarioms: "1.300"
dataref: "14/07/2020"
