theme: jekyll-theme-cayman
total: "1.193.762"
diario: "41.538"
obitos: "53.897"
obitosdiario: "1.105"
totalms: "1.188.631"
diarioms: "42.725"
obitosms: "53.830"
obitosdiarioms: "1.185"
dataref: "24/06/2020"
