theme: jekyll-theme-cayman
total: "3.463.133"
diario: "46.358"
obitos: "111.240"
obitosdiario: "1.140"
totalms: "3.456.652"
diarioms: "49.298"
obitosms: "111.100"
obitosdiarioms: "1.212"
dataref: "19/08/2020"
