theme: jekyll-theme-cayman
total: "1.807.900"
diario: "46.404"
obitos: "70.609"
obitosdiario: "1.320"
totalms: "1.800.820"
diarioms: "45.048"
obitosms: "70.398"
obitosdiarioms: "1.214"
dataref: "10/07/2020"
