theme: jekyll-theme-cayman
total: "2.235.076"
diario: "66.738"
obitos: "82.925"
obitosdiario: "1.292"
totalms: "2.227.514"
diarioms: "67.860"
obitosms: "82.771"
obitosdiarioms: "1.284"
dataref: "22/07/2020"
