theme: jekyll-theme-cayman
total: "1.675.264"
diario: "46.755"
obitos: "66.907"
obitosdiario: "1.307"
totalms: "1.668.589"
diarioms: "45.305"
obitosms: "66.741"
obitosdiarioms: "1.254"
dataref: "07/07/2020"
