theme: jekyll-theme-cayman
total: "2.100.718"
diario: "23.900"
obitos: "79.554"
obitosdiario: "701"
totalms: "2.098.389"
diarioms: "23.529"
obitosms: "79.488"
obitosdiarioms: "716"
dataref: "19/07/2020"
